// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.22.0
// source: user.sql

package sqlc

import (
	"context"
)

const createUser = `-- name: CreateUser :one
INSERT INTO users(username, password, email)
VALUES ($1, $2, $3)
RETURNING id, username, email, password
`

type CreateUserParams struct {
	Username string
	Password string
	Email    string
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRowContext(ctx, createUser, arg.Username, arg.Password, arg.Email)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Email,
		&i.Password,
	)
	return i, err
}

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT id,
    email,
    username,
    password
FROM users
WHERE email = $1
`

type GetUserByEmailRow struct {
	ID       int64
	Email    string
	Username string
	Password string
}

func (q *Queries) GetUserByEmail(ctx context.Context, email string) (GetUserByEmailRow, error) {
	row := q.db.QueryRowContext(ctx, getUserByEmail, email)
	var i GetUserByEmailRow
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Username,
		&i.Password,
	)
	return i, err
}

const getuserlist = `-- name: Getuserlist :many
SELECT id,
    username,
    email
FROM users
`

type GetuserlistRow struct {
	ID       int64
	Username string
	Email    string
}

func (q *Queries) Getuserlist(ctx context.Context) ([]GetuserlistRow, error) {
	rows, err := q.db.QueryContext(ctx, getuserlist)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetuserlistRow
	for rows.Next() {
		var i GetuserlistRow
		if err := rows.Scan(&i.ID, &i.Username, &i.Email); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
